# Keeping repository quality high.
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
      - id: black
        args: [ "--line-length=120" ]
  - repo: https://github.com/pycqa/isort
    rev: 7.0.0
    hooks:
      - id: isort
        args: [ "--profile", "black" ]
  - repo: https://github.com/pycqa/pylint
    rev: v4.0.1
    hooks:
      - id: pylint
        additional_dependencies: [ "gymnasium","numpy" ]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        args: [ "--strict" ]
        additional_dependencies: [ "types-requests", "types-PyYAML", "gymnasium","numpy" ]
  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        args: [ "--docstring-convention=numpy", "--max-line-length=120", "--ignore=D406,D407" ]
        additional_dependencies: [ "flake8-bugbear", "flake8-docstrings", "pydocstyle>=6.3.0" ]

  # We need to check this first! ruff would replace flake8-bugbear and might conflict with Black
  # flake8-bugbear is deprecated, so we want to use ruff instead
  # - repo: https://github.com/astral-sh/ruff-pre-commit
  #  rev: 0.14.1
  #  hooks:
  #    - id: ruff
  #      args: ["--fix"]
  #    - id: ruff-format
